### ISSUE TITLE
Use pretty-bytes for file sizes

### ISSUE THREAD

**Issue by jeffposnick** [jeffposnick/sw-precache#7]
@sindresorhus's https://github.com/sindresorhus/pretty-bytes can replace the function at https://github.com/jeffposnick/sw-precache/blob/00c2b0bc7ab785cae7446b3a166e83435c644f02/sw-precache.js#L43-L53

**Comment by rmacklin** [comment]
@jeffposnick This change also changed the output from KB (1024 bytes) to kB (1000 bytes), which is inconsistent with how Chrome's network tab displays file sizes (as well as how `ls` usually displays file sizes). Since Chrome displays the size in KB, I think having the tool output sizes in kB can be confusing. I can understand generally wanting to use npm packages instead of hand-rolled functions, but in this case the function was pretty simple and I think replacing it with pretty-bytes was actually a downgrade due to the KB/kB mismatch.

Is there any chance you'd be open to a PR reverting f2019145191bd0efa2467ccd37cf092d2b98362f, or is that outside the scope of maintenance for this repository (given that it's kind of deprecated by workbox)?

**Comment by jeffposnick** [comment]
I don't believe that this is something we'd change at this point in `sw-precache`'s lifespan.
